blank_issues_enabled: true
contact_links:
  - name: Meta
    url: https://github.com/The-TOG/meta/new/meta
    about: Discuss the TOG in general
  - name: MyG4mes Wiki
    url: https://github.com/The-TOG/MyG4mes/wiki
    about: Documentation and Q&A for MyG4mes
